### ISSUE TITLE
 unable to reach server at: http://engineerolabs.github.io/Process_LaTeX/

### ISSUE THREAD

**Issue by SergeevGregory** [Engineero/latex_in_word#1]
Dear developers,
I downloaded latex_in_word_2010.docm and tried to modify Latex equation. When I clicked "Convert" button error occurred: unable to reach server at: http://engineerolabs.github.io/Process_LaTeX/

Hope you will fix it. I have old big document with "latex in word" and now can't edit equations. Old and new servers don't work :(

**Comment by Engineero** [comment]
Try out the Windows-only release or the most recent Docker release. Both of those should be able to run on your local machine without needing to call out.

Unfortunately we lost access to the server that we were using and I have been unable to set up a new remote server as of yet. If you know how to get LaTeX running on github.io or a similar service and want to help out that would be cool too!

**Comment by Engineero** [comment]
I am going to close this, but feel free to reopen if you like. The Windows-only release should get you up and running without the need to dial out to a server.
