### ISSUE TITLE
New Online Server?

### ISSUE THREAD

**Issue by ManjuO** [Engineero/latex_in_word#2]
Hi. I'm using the LaTeX in WOrd macro (THANKYOU!) but it doesn't find the server "Base_Web_Address = "http://engineerolabs.github.io/Process_LaTeX/"

Is there a new server location or do I have to set up my own (programming makes me cry, so I hope not.)
![image](https://user-images.githubusercontent.com/63151192/78450621-3b3d8380-7680-11ea-9bb1-edaeee123467.png)

**Comment by Engineero** [comment]
Check out the [Process_LaTeX repo](https://github.com/EngineeroLabs/Process_LaTeX) for some other options including a native Windows server that you can run on your machine. Unfortunately I am not really supporting this package anymore and have not personally gotten the Windows or Docker server up and running. If you are able to do so, I encourage you to submit updates to the documentation to help others in the future.

Sorry I can't be more help.

**Comment by ManjuO** [comment]
Thank you for writing the macro in the first place! As for figuring out the server, I could barely follow the client instructions. Figuring out the server installation would be something I get my bf’s 18yr old son to figure out. Way over my head, that.  Mvh,Manju Odland*The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future. From: EngineeroSent: Tuesday, April 7, 2020 8:05 PMTo: EngineeroLabs/latex_in_wordCc: ManjuO; AuthorSubject: Re: [EngineeroLabs/latex_in_word] New Online Server? (#2) Check out the Process_LaTeX repo for some other options including a native Windows server that you can run on your machine. Unfortunately I am not really supporting this package anymore and have not personally gotten the Windows or Docker server up and running. If you are able to do so, I encourage you to submit updates to the documentation to help others in the future.Sorry I can't be more help.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ManjuO** [comment]
Hi, By the way…https://support.office.com/en-us/article/linear-format-equations-using-unicodemath-and-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8 Seems it’s already added.  Mvh,Manju Odland+4795088483*The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future. From: EngineeroSent: Tuesday, April 7, 2020 8:05 PMTo: EngineeroLabs/latex_in_wordCc: ManjuO; AuthorSubject: Re: [EngineeroLabs/latex_in_word] New Online Server? (#2) Check out the Process_LaTeX repo for some other options including a native Windows server that you can run on your machine. Unfortunately I am not really supporting this package anymore and have not personally gotten the Windows or Docker server up and running. If you are able to do so, I encourage you to submit updates to the documentation to help others in the future.Sorry I can't be more help.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
